### ISSUE TITLE
crypto-pubkey-0.2.8 fails its test suite

### ISSUE THREAD

**Issue by peti** [vincenthz/hs-crypto-pubkey#20]
The file `KATs/ECC-PKV.txt` seems to be missing: http://hydra.nixos.org/build/18992568/nixlog/1/raw.

**Comment by peti** [comment]
ping?

**Comment by nomeata** [comment]
This is still a problem.

**Comment by jdnavarro** [comment]
That file is present in the `kat` branch: https://github.com/vincenthz/hs-crypto-pubkey/tree/kat/KATs. @vincenthz, can that branch be merged into `master`?
